### PR TITLE
Continue from PR to Ombi to integrate LDAP

### PR DESCRIPTION
**Pull request by Paannda**
Hello ! 
I saw your work regarding [this PR](https://github.com/Ombi-app/Ombi/pull/3805) and wanted to give you a hand in order to finish the work. This seems to be working fine in my setup. 
The change that are for now in this pull request : 
- Correcting Unit test so they can pass
- Modify user type to 6 to comply with [this PR](https://github.com/Ombi-app/Ombi/pull/3924)
- Correcting the variable name complaint in LdapUserImporter.cs
- Moving to the UI the hint instead of using the constructor in LdapSettings.cs

I hope this can help, I plan on continue working on this so that we can satisfy all the request from @tidusjar
Cheers !

### CODE REVIEW

**Comment by tidusjar** [comment]
Thanks a lot for picking this up!

My main concern with this is I do not currently have the correct setup to support and test this. 

Please appreciate that I still need to support this feature in the years to come! 

But I will start looking into getting this setup over the next week!

**Comment by Paannda** [comment]
Don't worry : I was not even hoping to see an acknowledgment so fast ! 
It will still take me some time for me to integrate every comment you made on the main PR

**Comment by Paannda** [comment]
I will close this pull-request, to start the work again from develop, since develop got a little bit ahead of feature/v4

**Comment by dpraul** [comment]
I forgot to put notifications on for this repo and never saw this. Thanks for picking this up where I left off! I definitely let it stagnate far too long. Are you still working on this elsewhere? I'm happy to UAT any of your changes once they're ready. Could potentially contribute some integration tests to make it easier to test & maintain.

**Pull request closed without merging**
